name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fastapi=0.116.1
  - uvicorn=0.35.0
  - sqlalchemy=2.0.43
  - pydantic=1.10.*
  - pyyaml=6.0.2
  - pip
  - pip:
      - asyncio-mqtt==0.16.2
      - minimalmodbus==2.1.1
